description: K1Plaza test site



widgets:
  Gallery:
    slider:
      title: Slider
  Blog:
    blog:
      title: Blog
      page_path: blog
  Expo:
    expo:
      title: Expo
      page_path: expo
# foo
# foo
# foo
# foo
